title: Rohan Kumar Thakur
email: your-email@example.com
description: >-
  My portfolio website showcasing photography, art, 
  technical projects, and miscellaneous content.

baseurl: ""
url: "https://rohankthakur.github.io/"
twitter_username: yourusername
github_username: rohankthakur
linkedin_username: rohanthakur
flickr_username: rohanthakur

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
    css_class: 'highlight'
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Pagination settings (using jekyll-paginate-v2)
#pagination:
#  enabled: true
#  per_page: 6
#  permalink: '/page/:num/'
#  title: ':title - Page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
#  collection: 'posts'
#  extension: html
#  indexpage: 'index'

# Category pagination
#autopages:
  #enabled: true
  #collections:
    #enabled: false
  #categories:
    #layouts: ['category.html']
    #title: ':cat'
    #permalink: '/:cat/'
    #slugify:
      #mode: 'default'
      #case: false
  #tags:
    #layouts: ['tag.html']
    #title: 'Tagged: :tag'
    #permalink: '/tag/:tag/'

# Collections - not needed for post-based approach
# collections:

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rohan Kumar Thakur"
  - scope:
      path: ""
    values:
      layout: "default"

# GitHub Pages safe settings
safe: false  # Set to true for GitHub Pages, false for GitHub Actions
incremental: false
lsi: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - setup.sh
  - setup.bat
  - "*.bat"
  - "*.sh"

# Include
include:
  - .htaccess
  - _pages

# Timezone
timezone: Asia/Kolkata

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/
